-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgHeKZUsIk43JT1KME
L/1h1yswGWfzX3p85xURLcvUzwegCgYIKoZIzj0DAQehRANCAATPJBPrytJxOBt/
YdsNiPTW5g5c6uF+cQF9qMQlEcoQVb8Jl5Yc/zfW6ThbAckV3lYs5Kb/rZy3QIUp
d9/7P+pq
-----END PRIVATE KEY-----
